version: '3.8'

services:

  webhook:
    image: viniaamorim/webhook
    ports:
      - "8080:8080"
    environment:
      - WAHAA_URL=http://api:3000

  api:
    image: viniaamorim/api-whatsapp-web-js
    ports:
      - "3000:3000"
    depends_on:
      - webhook
    environment:
      - WEBHOOK_URL=http://webhook:8080

